import type { Medicine } from '@/types';

export const SAMPLE_MEDICINES: Medicine[] = [
  {
    id: 'med-1',
    pharmacy_id: 'pharma-1',
    name: 'Paracetamol',
    brand: 'Dolo 650 / Crocin',
    generic_name: 'Paracetamol (Acetaminophen)',
    batch_number: 'PCM-2026-01',
    expiry_date: '2027-12-31',
    quantity: 150,
    price: 25,
    discount: 0,
    prescription_required: false,
    category: 'Fever / Pain',
    description: 'Relieves fever, mild to moderate headaches, muscle aches, and body pain.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '500 mg',
    manufacturer: 'Micro Labs Ltd',
  },
  {
    id: 'med-2',
    pharmacy_id: 'pharma-1',
    name: 'Ibuprofen',
    brand: 'Brufen 400',
    generic_name: 'Ibuprofen',
    batch_number: 'IBU-2026-02',
    expiry_date: '2027-10-31',
    quantity: 120,
    price: 35,
    discount: 5,
    prescription_required: false,
    category: 'Pain / Inflammation',
    description: 'Non-steroidal anti-inflammatory drug (NSAID) for joint pain, swelling, and toothaches.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '400 mg',
    manufacturer: 'Abbott India',
  },
  {
    id: 'med-3',
    pharmacy_id: 'pharma-1',
    name: 'Cetirizine',
    brand: 'Cetzine / Okacet',
    generic_name: 'Cetirizine Hydrochloride',
    batch_number: 'CET-2026-03',
    expiry_date: '2028-03-31',
    quantity: 200,
    price: 20,
    discount: 0,
    prescription_required: false,
    category: 'Allergy',
    description: 'Antihistamine for sneezing, runny nose, watery eyes, and allergic skin rashes.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '10 mg',
    manufacturer: 'Cipla',
  },
  {
    id: 'med-4',
    pharmacy_id: 'pharma-1',
    name: 'Levocetirizine',
    brand: 'LCC / Levocet',
    generic_name: 'Levocetirizine Dihydrochloride',
    batch_number: 'LVC-2026-04',
    expiry_date: '2027-08-31',
    quantity: 180,
    price: 45,
    discount: 10,
    prescription_required: false,
    category: 'Allergy',
    description: 'Fast-acting second-generation antihistamine for seasonal allergies and rhinitis.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '5 mg',
    manufacturer: "Dr. Reddy's Laboratories",
  },
  {
    id: 'med-5',
    pharmacy_id: 'pharma-1',
    name: 'Loratadine',
    brand: 'Lorfast / Claritin',
    generic_name: 'Loratadine',
    batch_number: 'LOR-2026-05',
    expiry_date: '2027-11-30',
    quantity: 110,
    price: 50,
    discount: 5,
    prescription_required: false,
    category: 'Allergy',
    description: 'Non-drowsy antihistamine for hay fever, hives, and pollen allergy.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '10 mg',
    manufacturer: 'Cadila Healthcare',
  },
  {
    id: 'med-6',
    pharmacy_id: 'pharma-1',
    name: 'Azithromycin',
    brand: 'Azithral 500',
    generic_name: 'Azithromycin Dihydrate',
    batch_number: 'AZI-2026-06',
    expiry_date: '2027-06-30',
    quantity: 75,
    price: 120,
    discount: 10,
    prescription_required: true,
    category: 'Antibiotic',
    description: 'Macrolide antibiotic for respiratory tract, ear, throat, and skin infections.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '500 mg',
    manufacturer: 'Cipla',
  },
  {
    id: 'med-7',
    pharmacy_id: 'pharma-1',
    name: 'Amoxicillin',
    brand: 'Mox 500 / Novamox',
    generic_name: 'Amoxicillin Trihydrate',
    batch_number: 'AMX-2026-07',
    expiry_date: '2027-05-31',
    quantity: 90,
    price: 85,
    discount: 5,
    prescription_required: true,
    category: 'Antibiotic',
    description: 'Penicillin-type antibiotic for chest infections, dental abscesses, and UTIs.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Capsule',
    strength: '500 mg',
    manufacturer: 'GlaxoSmithKline (GSK)',
  },
  {
    id: 'med-8',
    pharmacy_id: 'pharma-1',
    name: 'Cefixime',
    brand: 'Taxim-O 200 / Zifi',
    generic_name: 'Cefixime Trihydrate',
    batch_number: 'CFX-2026-08',
    expiry_date: '2027-09-30',
    quantity: 60,
    price: 140,
    discount: 8,
    prescription_required: true,
    category: 'Antibiotic',
    description: 'Cephalosporin antibiotic for typhoid fever, urinary tract, and ENT infections.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '200 mg',
    manufacturer: 'Alkem Laboratories',
  },
  {
    id: 'med-9',
    pharmacy_id: 'pharma-1',
    name: 'Doxycycline',
    brand: 'Doxypal / Doxy-1',
    generic_name: 'Doxycycline Hyclate',
    batch_number: 'DOX-2026-09',
    expiry_date: '2027-04-30',
    quantity: 80,
    price: 95,
    discount: 5,
    prescription_required: true,
    category: 'Antibiotic',
    description: 'Tetracycline antibiotic for bacterial infections, severe acne, and vector-borne fevers.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Capsule',
    strength: '100 mg',
    manufacturer: 'Sun Pharma',
  },
  {
    id: 'med-10',
    pharmacy_id: 'pharma-1',
    name: 'Metronidazole',
    brand: 'Flagyl 400 / Metrogyl',
    generic_name: 'Metronidazole',
    batch_number: 'MTZ-2026-10',
    expiry_date: '2028-01-31',
    quantity: 100,
    price: 30,
    discount: 0,
    prescription_required: true,
    category: 'Antimicrobial',
    description: 'Treats amoebic dysentery, gastrointestinal infections, and dental infections.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '400 mg',
    manufacturer: 'J.B. Chemicals & Pharmaceuticals',
  },
  {
    id: 'med-11',
    pharmacy_id: 'pharma-1',
    name: 'Omeprazole',
    brand: 'Omez 20',
    generic_name: 'Omeprazole Gastro-resistant',
    batch_number: 'OMP-2026-11',
    expiry_date: '2027-12-31',
    quantity: 130,
    price: 40,
    discount: 5,
    prescription_required: false,
    category: 'Acidity',
    description: 'Proton pump inhibitor (PPI) reducing stomach acid production and heartburn.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Capsule',
    strength: '20 mg',
    manufacturer: "Dr. Reddy's Laboratories",
  },
  {
    id: 'med-12',
    pharmacy_id: 'pharma-1',
    name: 'Pantoprazole',
    brand: 'Pan-40 / Pantocid',
    generic_name: 'Pantoprazole Sodium',
    batch_number: 'PNT-2026-12',
    expiry_date: '2028-02-28',
    quantity: 140,
    price: 55,
    discount: 10,
    prescription_required: false,
    category: 'Acidity',
    description: 'Relieves severe acid reflux, GERD, and stomach ulcers.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '40 mg',
    manufacturer: 'Torrent Pharmaceuticals',
  },
  {
    id: 'med-13',
    pharmacy_id: 'pharma-1',
    name: 'Famotidine',
    brand: 'Famocid 20',
    generic_name: 'Famotidine',
    batch_number: 'FAM-2026-13',
    expiry_date: '2027-07-31',
    quantity: 90,
    price: 25,
    discount: 0,
    prescription_required: false,
    category: 'Acidity',
    description: 'H2 receptor blocker providing rapid relief from indigestion and stomach gas.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '20 mg',
    manufacturer: 'Sun Pharma',
  },
  {
    id: 'med-14',
    pharmacy_id: 'pharma-1',
    name: 'Ondansetron',
    brand: 'Emeset 4 / Vomikind',
    generic_name: 'Ondansetron Hydrochloride',
    batch_number: 'OND-2026-14',
    expiry_date: '2027-10-31',
    quantity: 110,
    price: 48,
    discount: 5,
    prescription_required: true,
    category: 'Nausea / Vomiting',
    description: 'Prevents nausea and vomiting caused by stomach bugs, motion sickness, or medical treatments.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '4 mg',
    manufacturer: 'Cipla',
  },
  {
    id: 'med-15',
    pharmacy_id: 'pharma-1',
    name: 'ORS (Oral Rehydration Salts)',
    brand: 'Electral / W.H.O. ORS',
    generic_name: 'Oral Rehydration Salts (WHO Formula)',
    batch_number: 'ORS-2026-15',
    expiry_date: '2028-06-30',
    quantity: 300,
    price: 18,
    discount: 0,
    prescription_required: false,
    category: 'Dehydration',
    description: 'Essential electrolyte powder to restore lost fluid balance during diarrhea or fever.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Sachet',
    strength: '21.8 g',
    manufacturer: 'FDC Limited',
  },
  {
    id: 'med-16',
    pharmacy_id: 'pharma-1',
    name: 'Zinc Sulphate',
    brand: 'Zocon / Zincvit',
    generic_name: 'Zinc Sulphate Monohydrate',
    batch_number: 'ZNC-2026-16',
    expiry_date: '2028-04-30',
    quantity: 250,
    price: 30,
    discount: 0,
    prescription_required: false,
    category: 'Zinc Supplement',
    description: 'Supports immune function, wound healing, and pediatric diarrhea recovery.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '20 mg',
    manufacturer: 'Wallace Pharmaceuticals',
  },
  {
    id: 'med-17',
    pharmacy_id: 'pharma-1',
    name: 'Calcium Carbonate',
    brand: 'Shelcal 500',
    generic_name: 'Calcium Carbonate + Vitamin D3',
    batch_number: 'CLC-2026-17',
    expiry_date: '2027-09-30',
    quantity: 160,
    price: 75,
    discount: 8,
    prescription_required: false,
    category: 'Calcium Supplement',
    description: 'Strengthens bones, teeth, and supports bone density during pregnancy and aging.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '500 mg',
    manufacturer: 'Torrent Pharmaceuticals',
  },
  {
    id: 'med-18',
    pharmacy_id: 'pharma-1',
    name: 'Vitamin D3',
    brand: 'Calcirol 60K / Uprise D3',
    generic_name: 'Cholecalciferol (Vitamin D3)',
    batch_number: 'VD3-2026-18',
    expiry_date: '2028-05-31',
    quantity: 140,
    price: 110,
    discount: 10,
    prescription_required: false,
    category: 'Vitamin Supplement',
    description: 'High-potency weekly Vitamin D3 supplement for immunity and bone health.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Sachet',
    strength: '60,000 IU',
    manufacturer: 'Cadila Healthcare',
  },
  {
    id: 'med-19',
    pharmacy_id: 'pharma-1',
    name: 'Ferrous Sulfate',
    brand: 'Autrin / Fefol',
    generic_name: 'Ferrous Sulfate + Folic Acid',
    batch_number: 'FES-2026-19',
    expiry_date: '2027-11-30',
    quantity: 200,
    price: 45,
    discount: 5,
    prescription_required: false,
    category: 'Iron Supplement',
    description: 'Treats iron-deficiency anemia, fatigue, and replenishes hemoglobin levels.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '100 mg',
    manufacturer: 'Pfizer India',
  },
  {
    id: 'med-20',
    pharmacy_id: 'pharma-1',
    name: 'Folic Acid',
    brand: 'Folvite 5mg',
    generic_name: 'Folic Acid (Vitamin B9)',
    batch_number: 'FOL-2026-20',
    expiry_date: '2028-03-31',
    quantity: 220,
    price: 22,
    discount: 0,
    prescription_required: false,
    category: 'Folate Supplement',
    description: 'Crucial prenatal nutrient for red blood cell synthesis and fetal neural development.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '5 mg',
    manufacturer: 'Cipla',
  },
  {
    id: 'med-21',
    pharmacy_id: 'pharma-1',
    name: 'Multivitamin',
    brand: 'Becosules Z / Supradyn',
    generic_name: 'B-Complex + Vitamin C + Zinc',
    batch_number: 'MTV-2026-21',
    expiry_date: '2027-12-31',
    quantity: 180,
    price: 135,
    discount: 12,
    prescription_required: false,
    category: 'Nutritional Supplement',
    description: 'Daily multivitamin capsule boost for stamina, skin health, and energy metabolism.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Capsule',
    strength: 'Daily Formula',
    manufacturer: 'Pfizer India',
  },
  {
    id: 'med-22',
    pharmacy_id: 'pharma-1',
    name: 'Albendazole',
    brand: 'Zentel 400 / Bandy',
    generic_name: 'Albendazole',
    batch_number: 'ALB-2026-22',
    expiry_date: '2027-08-31',
    quantity: 85,
    price: 18,
    discount: 0,
    prescription_required: true,
    category: 'Deworming',
    description: 'Broad-spectrum antihelminthic for intestinal worm infestations in children and adults.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Chewable Tablet',
    strength: '400 mg',
    manufacturer: 'GlaxoSmithKline (GSK)',
  },
  {
    id: 'med-23',
    pharmacy_id: 'pharma-1',
    name: 'Mebendazole',
    brand: 'Mebex 100',
    generic_name: 'Mebendazole',
    batch_number: 'MEB-2026-23',
    expiry_date: '2027-06-30',
    quantity: 70,
    price: 24,
    discount: 0,
    prescription_required: true,
    category: 'Deworming',
    description: 'Deworming tablet for pinworm, roundworm, and hookworm infections.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '100 mg',
    manufacturer: 'Janssen Pharmaceuticals',
  },
  {
    id: 'med-24',
    pharmacy_id: 'pharma-1',
    name: 'Domperidone',
    brand: 'Vomistop / Domstal',
    generic_name: 'Domperidone Maleate',
    batch_number: 'DOM-2026-24',
    expiry_date: '2027-10-31',
    quantity: 125,
    price: 38,
    discount: 5,
    prescription_required: true,
    category: 'Nausea / Gastric Symptoms',
    description: 'Prokinetic medicine relieving upper abdominal bloating, nausea, and fullness.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '10 mg',
    manufacturer: 'Torrent Pharmaceuticals',
  },
  {
    id: 'med-25',
    pharmacy_id: 'pharma-1',
    name: 'Lactulose',
    brand: 'Duphalac Syrup',
    generic_name: 'Lactulose Concentrate',
    batch_number: 'LAC-2026-25',
    expiry_date: '2028-02-28',
    quantity: 65,
    price: 160,
    discount: 10,
    prescription_required: false,
    category: 'Constipation',
    description: 'Gentle osmotic laxative syrup softening stools without causing cramping.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Syrup',
    strength: '10 g / 15 ml',
    manufacturer: 'Abbott India',
  },
  {
    id: 'med-26',
    pharmacy_id: 'pharma-1',
    name: 'Bisacodyl',
    brand: 'Dulcolax 5',
    generic_name: 'Bisacodyl',
    batch_number: 'BIS-2026-26',
    expiry_date: '2027-09-30',
    quantity: 190,
    price: 12,
    discount: 0,
    prescription_required: false,
    category: 'Constipation',
    description: 'Overnight stimulant laxative for temporary constipation relief.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '5 mg',
    manufacturer: 'Sanofi India',
  },
  {
    id: 'med-27',
    pharmacy_id: 'pharma-1',
    name: 'Salbutamol',
    brand: 'Asthalin Inhaler',
    generic_name: 'Salbutamol Sulphate (Albuterol)',
    batch_number: 'SAL-2026-27',
    expiry_date: '2027-07-31',
    quantity: 50,
    price: 145,
    discount: 5,
    prescription_required: true,
    category: 'Breathing Conditions',
    description: 'Fast-acting bronchodilator inhaler providing immediate asthma attack relief.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Inhaler',
    strength: '100 mcg',
    manufacturer: 'Cipla',
  },
  {
    id: 'med-28',
    pharmacy_id: 'pharma-1',
    name: 'Montelukast',
    brand: 'Montek-LC / Romilast',
    generic_name: 'Montelukast Sodium + Levocetirizine',
    batch_number: 'MON-2026-28',
    expiry_date: '2027-11-30',
    quantity: 95,
    price: 110,
    discount: 10,
    prescription_required: true,
    category: 'Allergy / Asthma Management',
    description: 'Leukotriene receptor antagonist controlling chronic allergic rhinitis and asthma.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '10 mg',
    manufacturer: 'Sun Pharma',
  },
  {
    id: 'med-29',
    pharmacy_id: 'pharma-1',
    name: 'Budesonide',
    brand: 'Budecort 200 / Pulmicort',
    generic_name: 'Budesonide',
    batch_number: 'BUD-2026-29',
    expiry_date: '2027-05-31',
    quantity: 40,
    price: 210,
    discount: 15,
    prescription_required: true,
    category: 'Respiratory Conditions',
    description: 'Inhaled corticosteroid reducing airway swelling and preventing asthma flare-ups.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Inhaler',
    strength: '200 mcg',
    manufacturer: 'Cipla',
  },
  {
    id: 'med-30',
    pharmacy_id: 'pharma-1',
    name: 'Diclofenac',
    brand: 'Voveran SR / Diclogesic',
    generic_name: 'Diclofenac Sodium',
    batch_number: 'DIC-2026-30',
    expiry_date: '2027-09-30',
    quantity: 140,
    price: 42,
    discount: 5,
    prescription_required: true,
    category: 'Pain / Inflammation',
    description: 'Potent pain relief for arthritis, joint injuries, and post-surgical swelling.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '50 mg',
    manufacturer: 'Novartis India',
  },
  {
    id: 'med-31',
    pharmacy_id: 'pharma-1',
    name: 'Naproxen',
    brand: 'Naprosyn 500',
    generic_name: 'Naproxen Sodium',
    batch_number: 'NPX-2026-31',
    expiry_date: '2027-10-31',
    quantity: 85,
    price: 65,
    discount: 5,
    prescription_required: true,
    category: 'Pain / Inflammation',
    description: 'Long-acting anti-inflammatory for chronic joint pain, gout, and migraine relief.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '500 mg',
    manufacturer: 'RPG Life Sciences',
  },
  {
    id: 'med-32',
    pharmacy_id: 'pharma-1',
    name: 'Antacid Suspension',
    brand: 'Gelusil MPS / Digene',
    generic_name: 'Aluminum Hydroxide + Magnesium Hydroxide + Simethicone',
    batch_number: 'ANT-2026-32',
    expiry_date: '2028-04-30',
    quantity: 110,
    price: 125,
    discount: 8,
    prescription_required: false,
    category: 'Acidity',
    description: 'Mint-flavored liquid antacid neutralizing stomach acid and relieving flatulence.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Suspension',
    strength: '200 ml',
    manufacturer: 'Abbott India',
  },
  {
    id: 'med-33',
    pharmacy_id: 'pharma-1',
    name: 'Povidone-Iodine',
    brand: 'Betadine Ointment 5%',
    generic_name: 'Povidone-Iodine',
    batch_number: 'PVI-2026-33',
    expiry_date: '2028-03-31',
    quantity: 150,
    price: 60,
    discount: 0,
    prescription_required: false,
    category: 'Antiseptic',
    description: 'Topical antiseptic ointment preventing infection in minor cuts, scrapes, and burns.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Ointment',
    strength: '5% w/w',
    manufacturer: 'Win-Medicare',
  },
  {
    id: 'med-34',
    pharmacy_id: 'pharma-1',
    name: 'Chlorhexidine',
    brand: 'Clohex Mouthwash',
    generic_name: 'Chlorhexidine Gluconate',
    batch_number: 'CHX-2026-34',
    expiry_date: '2027-12-31',
    quantity: 120,
    price: 95,
    discount: 5,
    prescription_required: false,
    category: 'Antiseptic',
    description: 'Antiseptic oral rinse for gum inflammation, mouth ulcers, and plaque control.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Mouthwash',
    strength: '0.2% w/v',
    manufacturer: 'ICPA Health Products',
  },
  {
    id: 'med-35',
    pharmacy_id: 'pharma-1',
    name: 'Calamine Lotion',
    brand: 'Lacto Calamine',
    generic_name: 'Calamine + Zinc Oxide Lotion',
    batch_number: 'CLM-2026-35',
    expiry_date: '2028-06-30',
    quantity: 130,
    price: 140,
    discount: 10,
    prescription_required: false,
    category: 'Skin Irritation',
    description: 'Soothes sunburn, insect bites, prickly heat rash, and skin itching.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Lotion',
    strength: '120 ml',
    manufacturer: 'Piramal Pharma',
  },
  {
    id: 'med-36',
    pharmacy_id: 'pharma-1',
    name: 'Clotrimazole',
    brand: 'Candid Cream / Dusting Powder',
    generic_name: 'Clotrimazole',
    batch_number: 'CLT-2026-36',
    expiry_date: '2028-01-31',
    quantity: 160,
    price: 75,
    discount: 5,
    prescription_required: false,
    category: 'Fungal Skin Infections',
    description: 'Broad-spectrum antifungal cream treating ringworm, athlete foot, and fungal rashes.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Cream',
    strength: '1% w/w',
    manufacturer: 'Glenmark Pharmaceuticals',
  },
  {
    id: 'med-37',
    pharmacy_id: 'pharma-1',
    name: 'Mupirocin',
    brand: 'T-Bact Ointment',
    generic_name: 'Mupirocin',
    batch_number: 'MUP-2026-37',
    expiry_date: '2027-08-31',
    quantity: 75,
    price: 135,
    discount: 10,
    prescription_required: true,
    category: 'Bacterial Skin Infections',
    description: 'Topical antibiotic ointment for impetigo, folliculitis, and infected skin wounds.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Ointment',
    strength: '2% w/w',
    manufacturer: 'GlaxoSmithKline (GSK)',
  },
  {
    id: 'med-38',
    pharmacy_id: 'pharma-1',
    name: 'Amlodipine',
    brand: 'Amlopress 5 / Stamlo',
    generic_name: 'Amlodipine Besylate',
    batch_number: 'AML-2026-38',
    expiry_date: '2027-11-30',
    quantity: 150,
    price: 28,
    discount: 0,
    prescription_required: true,
    category: 'Blood Pressure',
    description: 'Calcium channel blocker managing hypertension (high BP) and preventing angina.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '5 mg',
    manufacturer: 'Cipla',
  },
  {
    id: 'med-39',
    pharmacy_id: 'pharma-1',
    name: 'Metformin',
    brand: 'Glycomet 500 SR',
    generic_name: 'Metformin Hydrochloride SR',
    batch_number: 'MET-2026-39',
    expiry_date: '2028-02-28',
    quantity: 180,
    price: 32,
    discount: 0,
    prescription_required: true,
    category: 'Type 2 Diabetes',
    description: 'First-line oral anti-diabetic medication lowering blood glucose levels in Type 2 Diabetes.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '500 mg',
    manufacturer: 'USV Private Limited',
  },
  {
    id: 'med-40',
    pharmacy_id: 'pharma-1',
    name: 'Atorvastatin',
    brand: 'Atorva 10 / Lipitor',
    generic_name: 'Atorvastatin Calcium',
    batch_number: 'ATV-2026-40',
    expiry_date: '2027-10-31',
    quantity: 140,
    price: 70,
    discount: 5,
    prescription_required: true,
    category: 'Cholesterol',
    description: 'Statin medication lowering LDL cholesterol and triglycerides to protect heart health.',
    image_url: null,
    created_at: new Date().toISOString(),
    form: 'Tablet',
    strength: '10 mg',
    manufacturer: 'Sun Pharma',
  },
];
